extends:
  - 'plugin:@typescript-eslint/recommended'
  - next/core-web-vitals
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
rules:
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - 'warn'
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
      caughtErrorsIgnorePattern: ^_
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/ban-ts-comment': warn
